apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka-clusters
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sciclon2/kafka-strimzi-playground.git
        revision: HEAD
        directories:
          - path: clusters/*/*/*
  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}-{{path.basename}}' 
    spec:
      project: default
      source:
        repoURL: https://github.com/sciclon2/kafka-strimzi-playground.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[2]}}' 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
