apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: payments-kafka
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: ephemeral
