apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker-a
  labels:
    strimzi.io/cluster: payments-kafka
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 3Gi
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker-b
  labels:
    strimzi.io/cluster: payments-kafka
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 3Gi
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker-c
  labels:
    strimzi.io/cluster: payments-kafka
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 3Gi
    deleteClaim: false
