apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: payments-kafka
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: ephemeral
