apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: test-user
  namespace: dev
  labels:
    strimzi.io/cluster: payments-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: test
          patternType: literal
        operations:
          - Read
          - Write
      - resource:
          type: group
          name: test-group
          patternType: literal
        operations:
          - Read
