apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-dev
  namespace: strimzi
spec:
  kafka:
    version: 4.2.0
    metadataVersion: "4.2"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
